### ISSUE TITLE
hicPro file format support

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/HiCExplorer#156]

**Comment by nservant** [comment]
.Hi Joachim,
Please find below my answers

-     you store matrices in a text file .matrix which is tab delimited and is of x y value, only non-zero values are stored.

Yes only non-zero values are stored, and by default only the upper part of the matrix is returned.
There is still an option to get the full matrix but it is not really used in practice.

-     the associated genomic positions for each bin are stored in a bed file with chr start end X, what is X?

Yes. X is a name. Again in most cases, this is not really useful if you work with whole genome Hi-C data. But the format was defined so that x and y (from the matrix file) can be names and not indices.
For instance, you could imagine to have ;
bin1 bin2 10
and this in the bed
chr1 1 10 bin1
chr5 1 10 bin2

But again, using names can be interesting for 5C for instance. But I think that most of the tools that allow to load HiC-Pro matrices just use the x, y as indices, and thus ignore the 4th column.

-     there are two bed files, _abs.bed and _ord.bed but with a scan of the files I don't see a difference. Is there any if yes what?

No, there is no difference. We still provide two files for historical reason (5C analysis) but I should update HiC-Pro to only report one file

-     In case of 'iced' data, there are no bed files. Does this mean there are non, or are these just the same as in the raw version and you don't wanted to store it twice?

This is because they are the same than for the raw data and I did not want to store them twice

-     Anything else to know before I start the implementation?

No basically, this is just a triplet sparse format + a bed file to describe the bins. That's it.

Thanks a lot,
Nicolas

**Comment by joachimwolff** [comment]
Thanks for your helpful information. The HiC-Pro file format will make it to the next 2.2 release which is planned for September (Maybe earlier, let's see :) ).
We will provided a read only support because we want to have one file format and not multiple for Hi-C data. I hope you understand this decision and will endorse cooler format too.

**Comment by joachimwolff** [comment]
One more question: Your matrix index starts with 1 and with 0?!

**Comment by joachimwolff** [comment]
For a first implementation see #257.
