### ISSUE TITLE
OverflowError using hicPlotMatrix --pca 

### ISSUE THREAD

**Issue by GinaRe** [deeptools/HiCExplorer#177]
I get the following error when trying to plot a bw file using --pca in hicPlotMatrix:
OverflowError: In draw_path_collection: Exceeded cell block limit

**Comment by joachimwolff** [comment]
Thanks for reporting this bug. Can you show me the full traceback and the exact command you were using? Additional information about the used matrix is helpful, please run hicInfo on your matrix and past this output too.

**Comment by GinaRe** [comment]
I tried plotting the matrix without the additional bw file in --pca. This works fine.
The bw file I want to plot using --pca is actually a ChIP-seq track.

Traceback (most recent call last):
  File ".../hicPlotMatrix", line 7, in <module>
    main()
  File ".../hicexplorer/hicPlotMatrix.py", line 572, in main
    plt.tight_layout()
  File ".../matplotlib/pyplot.py", line 1406, in tight_layout
    fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File ".../matplotlib/figure.py", line 1743, in tight_layout
    warnings.warn("This figure includes Axes that are not "
UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.

**Comment by joachimwolff** [comment]
Sorry for the late feedback. 
As far as I know this error is caused by empty areas in your bw track in relation to the bins. I see the following approaches that might help:
1. Try using the additional argument `--clearMaskedBins`
2. With `--region` you can define a more specific region that maybe excludes the problematic data in your bw track.
3. Same as `2` but on chromosome level: Use `--chromosomeOrder` to exclude problematic chromosomes.
If this all does not help I want to ask you if you could send me your data that I can debug it and we can fix this bug with the next release.

**Comment by GinaRe** [comment]
Thanks for your suggestions. Unfortunately all approaches lead to the same old error.

**Comment by GinaRe** [comment]
I will send you the files. Hope this helps to fix the problem.

**Comment by joachimwolff** [comment]
I think this issue is solved now, see 2.0.1-bugfix branch.
