### ISSUE TITLE
export zscore matrix to cool - open in HiGlass?

### ISSUE THREAD

**Issue by samuelCollombet** [deeptools/HiCExplorer#188]
Hi, 
I would like to export the matrix of zscore from findTADs to HiGlass. Have you ever tried to do that?

I managed to make a .cool from the h5 matrix but when i try to zoomify it I get the following error:
`$cooler zoomify TADs/HeardLab_mNPe_HiC_allValidPairs_G2.pairix.cool_zscore_matrix.h5.cool
INFO:cooler:Recursively aggregating "TADs/HeardLab_mNPe_HiC_allValidPairs_G2.pairix.cool_zscore_matrix.h5.cool"
INFO:cooler:Writing to "TADs/HeardLab_mNPe_HiC_allValidPairs_G2.pairix.mcool_zscore_matrix.h5.mcool"
Traceback (most recent call last):
  File "/usr/local/src/anaconda2/bin/cooler", line 6, in <module>
    sys.exit(cooler.cli.cli())
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/src/anaHave you conda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/cooler/cli/aggregate.py", line 367, in zoomify
    chunksize, lock=lock)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/cooler/cli/aggregate.py", line 79, in multires_aggregate
    n_zooms = get_quadtree_depth(clr.chromsizes, clr.binsize)
  File "/usr/local/src/anaconda2/lib/python2.7/site-packages/cooler/cli/aggregate.py", line 66, in get_quadtree_depth
    tile_size_bp = QUAD_TILE_SIZE_PIXELS * binsize
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
`
Thanks,
Samuel

**Comment by joachimwolff** [comment]
I never tried this but I think the problematic part here is the following:
Cooler uses integers to store the pixels (the contacts) and not floats. But the z-scores are floats, and more important to your error is that in Python the value `np.nan` which we use from time to time in our matrices is a float too. Converting your h5 to cooler will probably force the `np.nan` to be a `NoneType` and then you get the error you have. 
There is some workaround for cooler matrices to store floats, but it was only mentioned by the developers in an issue and is not really documented. Nevertheless, we use it because there is no otherway to store the corrected matrix. 

I am a bit surprised by the error message. It says that the `binsize` is of type `NoneType`.

Have you used our `hicExport` to convert it? Can you send me your h5 and the resulting cooler file? I could try to figure out what is wrong and (hopefully) patch it.

**Comment by gtrichard** [comment]
Should we investigate the compatibility of HiCExplorer output with HiGlass at some point?

**Comment by samuelCollombet** [comment]
It would be great! if I can help in anyway let me know. However we have made some other tests here trying to export some normalized matrix from HicPro to HiGlass, and we had the same problem with the zoomify step. We think zoomify has a problem with floating number, which could be the problem for the Zscore matrix as well. 
Let me know if you find anything else.

**Comment by joachimwolff** [comment]
Hi, 

HiGlass works only with multi-cooler matrices, the z-score issue is already open somewhere else.

You can create mcool matrices with hicConvertFormat.

Best,

Joachim
