### ISSUE TITLE
hicPlotMatrix

### ISSUE THREAD

**Issue by GinaRe** [deeptools/HiCExplorer#194]
When using hicPlotMatrix --perChromosome the title (-t 'blabla') is not printed in the image.
Additionally, the default --scoreName is printed as "None" but should by empty instead.

**Comment by joachimwolff** [comment]
I can not reproduce this. Title is shown and no score name in the first image, in the second we have the score name 'foo'.
![bla](https://user-images.githubusercontent.com/13435136/36206049-4429e4d0-1191-11e8-82f6-828d0ac2d6fd.png)
![bla](https://user-images.githubusercontent.com/13435136/36206086-62d0eeba-1191-11e8-8c2c-15dbed988c96.png)

Which version (branch?) of HiCExplorer are you using?

**Comment by GinaRe** [comment]
I am using hicexplorer-1.8.1

![hicplotmatrix_perchromosome](https://user-images.githubusercontent.com/34270162/36310210-9bbd00a0-1327-11e8-8ce9-101c8221561f.png)

hicPlotMatrix -m Dmel.h5 -o ./plots/hicPlotMatrix_perChr.png -t 'D.melanogaster (--perChromosome)' --log1p --clearMaskedBins --dpi 300 --chromosomeOrder 2L 2R 3L 3R X --perChromosome

**Comment by joachimwolff** [comment]
Can you try the up to date version 2.0? I recommend to use conda and install version 2.0 in its own environment, and in a second environment version 1.8.1.

**Comment by GinaRe** [comment]
I tried version 2.0. I get the title but the plot looks quite different
![hicplotmatrix_perchromosome](https://user-images.githubusercontent.com/34270162/36314976-cb007bb2-1336-11e8-9ecb-16df40ed764c.png)

**Comment by gtrichard** [comment]
Isn't that a Masked Bins issue? If you "remove" the new big blocks that seems to appear with HiCExplorer 2.0, the heatmaps are the same. 

For example the "Cross" at the bottom right of the second plot is still there but it's shifted a bit more to the bottom right with 2.0 because these huge bins are included. You can clearly see if with the "20Mb" tick.

**Comment by joachimwolff** [comment]
Apart from the maybe missing `--clearMaskedBins` in 2.0 all the matrices have their own scale. I think this is something we need to implement as it was in 1.8 because it is better comparable.

**Comment by GinaRe** [comment]
I did use ``--clearMaskedBins`` actually after I saw this blocks but it didn't change anything. As you said this function is missing probably.

**Comment by joachimwolff** [comment]
@GinaRe  Can you send me the matrix? I will debug it to fix this issue.

**Comment by fidelram** [comment]
Hi, what is causing the problem is my latest 'improvements' of the code. In version 1.8 each bin is represented as a pixed of the same size, even if the bins have different sizes. This was corrected in the 2.0 version to allow the bigwig tracks to be plotted accurately with respect with the bins. In other words, the new matrices are base pair accurate while the previous were not. 

This brings a second problem: If the masked bins are removed, this creates gaps in the matrix that would not be represented on the bigwig tracks. Thus, we can not simply remove the masked bins a before because this will shrink the matrix. Thus, my solution was to use the same method used in `hicPlotTADs` which is to 'enlarge near bins' to occupy the space of the masked bins. That's why, the second image sent by Gina has the enlarged corners in some chromosomes.

I don't know how to solve the issue but I think that by explaining it you may provide some solutions.

**Comment by joachimwolff** [comment]
Maybe we set the areas in the matrix and in the bigwig plot to `0` and visualize these areas in the matrix as black (assuming black is not used in the color scheme) and on the bigwig track a 0 just means 'no value'.

**Comment by GinaRe** [comment]
Do you want the matrix to try out how it would look like? I could send it to you

**Comment by fidelram** [comment]
@joachimwolff I see two cases: One, which contains the 'masked bins'. In this case the Hi-C matrix and the bigwig should match. The masked bin color is blue at the moment but could be black as you say.

The second case is the more problematic because removing the masked bin also requires removing  the corresponding bigwig values. After erasing the bigwig values corresponding to the missing bin the track will continuous unless we put some marking to show that something was deleted. Also, the ticks for the coordinate positions will be affected.

I think that the best way to solve this issue is by describing what means --clearMaskedBins which just enlarges the near bins over the removed bins.

**Comment by fidelram** [comment]
@gtrichard That should help. Also, I have a number of changes in the pull request https://github.com/deeptools/HiCExplorer/pull/223 (based on branch `fix_plotHiC_matrix_on_small_chromosomes`) that should address some of the issues.

All my tests pass locally, but I have not managed to pass the tests on travis.
