### ISSUE TITLE
Build failing in python 3.6 - hicAggregateContacts

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCExplorer#197]
Hello,

I checked Travis CI building of the documentation branch and I saw that the build is failing only in python 3.6 at the test_hicAggregateContacts_3d step, you can check the error messages here:

https://travis-ci.org/deeptools/HiCExplorer/jobs/341337111

**Comment by joachimwolff** [comment]
@gtrichard Should be fixed. 
@all Please use `from __future__ import division
` instead of the Python 2 standard division. It is difficult for me to figure out where an integer division is wanted (e.g. if the values should be used as indices like it was in this case) or where it should be a floating one. Using the division from `__future__` uses the Python 3 method i.e. `5 / 3 = 1.666` and not `5 / 3 = 1` anymore. To use integer division use `5 // 3 = 1`.
@fidelram Please check in hicAggregateContacs if I am using the divisions as they were meant to be used.

**Comment by gtrichard** [comment]
@joachimwolff Could you push this modification to the documentation branch to see if the build is successful after these changes?

Otherwise, how should I proceed?
