### ISSUE TITLE
TAD-sep score between 3 different replicates

### ISSUE THREAD

**Issue by apaytuvi** [deeptools/HiCExplorer#211]
Hi,

I have 3 lines with different levels of compactness: high, medium and low. After ICE correction, I normalized the matrices so the sum of all counts is 100.000.000. Afterwards, I have calculated the TAD-separation scores using your software, by disabling the calculation of the z-scores by setting `use_zscores=False` in the code.

Low compacted:
![image](https://user-images.githubusercontent.com/11228225/36684018-722d425e-1b1f-11e8-8944-94526806563f.png)
Medium compacted:
![image](https://user-images.githubusercontent.com/11228225/36684082-a0dacd74-1b1f-11e8-931c-fa33b51e66f9.png)
High compacted:
![image](https://user-images.githubusercontent.com/11228225/36684054-8e6691c8-1b1f-11e8-91f4-1dab58eb092c.png)
I plotted the TAD-sep scores for these 3 lines (1. high; 2. low; 3. medium):
![image](https://user-images.githubusercontent.com/11228225/36684177-d29cba48-1b1f-11e8-9fec-d2c79fc726b1.png)

I expected the low-compacted genome to have higher "standard deviation" than the medium-compacted, and the medium-compacted higher "standard deviation" than the high-compacted.

However, the medium-compacted seems to have less TAD-sep score than the high-compacted... Does it make sense to you? Or am I doing something wrong?

Thanks.

**Comment by fidelram** [comment]
I think that your results make sense but I don't know if I understand correctly. What you call low compactness seems to me like a normal cell Hi-C in interphase with clear TADs. The high compactness looks like a cell in mitosis.

If the tracks that you present are in the same order as the figures on top, I would say that for the interphase case you should expect higher variation which is what I see. Otherwise for the mitotic case I see less variation.

Did I miss something?
