### ISSUE TITLE
obs/exp

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#240]
May I ask how the code differentiate between obs = 0 and exp =0 while computing Libermann  obs/exp. As far as I understood obs/exp has been set to zero when denominator is 0 (exp = 0) and of course it is gonna be 0 when obs = 0. I wonder if it cause an issue while looking for pearson_corr afterwards.  Thanks!

**Comment by joachimwolff** [comment]
Hi Leily,

if the expected value is 0, the obs/exp is set to zero. See https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/utilities.py#L226

If obs is zero, obs/exp == 0 because `0 / x == 0 `. 

Just in case something went wrong somewhere, we check after for `Nan` and `Inf` values and replace them with `0`: https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/hicTransform.py#L66

I have not found issues so far using this method and pearson correlation. To compute the Pearson correlation we use numpy.corrrcoef: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.corrcoef.html

The given formula there should become zero only if one of the values is actually zero, and zero is having the meaning of 'there is no correlation, neither positive nor negative' in the Pearson correlation. If a column is zero, the eigenvector at this position will be zero too. See e.g. http://science.sciencemag.org/content/sci/suppl/2009/10/08/326.5950.289.DC1/Lieberman-Aiden.SOM.pdf page 22 Figure S1, chromosome 13 or 14. And this is what we want to have: No information in the eigenvector if there is no information in the contact matrix.

I hope that clarifies your concerns. If you see an error in the computation, than please let me know and we can improve the HiCExplorer.

Best,

Joachim

**Comment by LeilyR** [comment]
Hey Joachim,
Thanks a lot. In fact I even checked the affect of setting abs/exp = 0 when exp =0 on a data set, it seems doesn't do anything wrong to the pearson_corr. That was why I closed it myself. But thanks a lot for the explanation, it was very helpful.
Best,
Leily
