### ISSUE TITLE
hicexport to .cool

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCExplorer#258]
Hi, while exporting .h5 matrix to .cool matrix from fly genome noticed that .cool format has difficulty accepting chromosome names since they are combination of numbers and letters and the word 'chr'  is not mentioned in h5 format and i think it is not being added while changing the format to .cool. So, technically the cool matrix generated by hicexport cannot be used by any of the cooler tools. For the first issue I don't know if you guys can change anything but for the later one I assume it will be possible to change the name to chr+number rather than number only.  Also, did any of you by any chance use cooler before on fly genome that can tell me how to overcome this issue?

**Comment by joachimwolff** [comment]
Hi Leily,

as far as I know we use to build the matrix the chromosome names which are provided by the BAM files and therefore by the reference genome you used for mapping. 'chr' is only included in the naming if you use UCSC reference genomes but you at MPI use ensembl. The conversion is not trivial e.g. https://github.com/dpryan79/ChromosomeMappings/blob/master/GRCh37_UCSC2ensembl.txt (https://link.getmailspring.com/link/1528718588.local-03b4318a-9c04-v1.2.2-96fb3a99@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fdpryan79%2FChromosomeMappings%2Fblob%2Fmaster%2FGRCh37_UCSC2ensembl.txt&recipient=cmVwbHkrMDBjZDAxMDA4N2UwNWQzMmEwNjgzZTJlZGJiZjQ1ODJjNTliZWVmYzlhYzVmOWEzOTJjZjAwMDAwMDAxMTczNjI1ZWY5MmExNjljZTEzYmQxNTcyQHJlcGx5LmdpdGh1Yi5jb20%3D) these are 90+ lines of conversion needed.
And yes, we do not convert it when we export from h5 to cool, we just take what is there. I think the issue is not that other can't use it, I think it is more that other do expect UCSC annotation but you provide ensembl.

Best,
Joachim
----------------------------------------
Joachim Wolff
M.Sc. Computer Science
Bioinformatics Lab
Department of Computer Science
Albert-Ludwigs-University Freiburg
Georges-Koehler-Allee 079
D-79110 Freiburg

http://www.bioinf.uni-freiburg.de

**Comment by vivekbhr** [comment]
@LeilyR to sort out whether the issue was UCSC vs ensembl or drosophila vs human, could you try using the UCSC version of the drosophila annotations ?

**Comment by LeilyR** [comment]
It has to do with both. The ucsc vs ensemble issue was easy for me to resolve but the drosophila vs human is not, and I dont know if you can do much for it, maybe the ".cool" people should change their code since it is written  very specifically when it gets to the chr names.

**Comment by LeilyR** [comment]
I am not using the .cool output of hicexplorer as an input for cooltools but I assume if one wants to use it has to modify cooltools code to make it work first on flies chromosome arms and second on the Ensembl format vs UCSC format.
