### ISSUE TITLE
Error when trying to plot an .mcool node with hicPlotTADs

### ISSUE THREAD

**Issue by kalavattam** [deeptools/HiCExplorer#265]
Hi HiCExplorer crew,

I was able to use hicFindTADs with a specific node of an .mcool file, and now I am trying to plot the results with hicPlotTADs. However, I keep getting an error that the file cannot be found (see below), even though I am using the same format that I use with hicFindTADs, hicPlotMatrix, etc. Is it possible to plot an .mcool node with hicPlotTADs?

Thanks,
Kris

```
ERROR:hicexplorer.trackPlot:File in section [2. [hic]] not found:
pooled.mcool::/resolutions/2000

Traceback (most recent call last):
  File "/users/ala1zp/anaconda3/envs/py27_hicexp_v2-1-4_env/lib/python2.7/site-packages/hicexplorer/trackPlot.py", line 372, in check_file_exists
    open(name_with_tracks_path, 'r').close()
IOError: [Errno 2] No such file or directory: u'/pooled.mcool::/resolutions/2000'
```

**Comment by joachimwolff** [comment]
Hi Kris,

the error message looks for me that for some reasons it tries to access a file in the root directory `/pooled.mcool::/resolutions/2000` (please notice the leading `/`). I don't know right now why a relative path is not working but a workaround should be to use the absolute path instead of a relative one.

Best,

Joachim

**Comment by kalavattam** [comment]
Thanks, Joachim.
