### ISSUE TITLE
hicAggregateContacts all chromosomes at once

### ISSUE THREAD

**Issue by kalavattam** [deeptools/HiCExplorer#275]
Not sure where you all stand with respect to this, but I'd like to request a feature for `hicAggregateContacts`: the option to aggregate contacts from not just individual chromosomes, but from multiple and/or all chromosomes.

Thanks,
Kris

**Comment by gtrichard** [comment]
So currently there is an un-optimal way to do it. Use `--outFilePrefixMatrix` and then compute the average of the per chromosome matrices. It is not ideal as you compute average of averages, or median of medians. The best way to proceed would be to collect all intra chromosomal submatrices and compute the average or the median of these submatrices independently of the chromosome they come from, this would be rather easy to implement I think.

Otherwise if you would like you have inter chromosomal contacts taken into consideration, I think we need to heavily change how hicAggregateContacts works, and I don't know if it is really worth it has inter chromosomal contacts tend to be very sparse because of chromosomal territories.

**Comment by samuelCollombet** [comment]
Dear gautier, 

Yes i thought about option 1 but if you have quite different numbers of feature per chromosome (I do) it becomes problematic... 
I think it would be very cool to add an option to aggregate all chromosome. 

It would also be nice to be able aggregate trans contact but this should probably be done independently from the cis as the scale will be very different. 

Many thanks! 

⁣Sent from BlueMail ​

**Comment by samuelCollombet** [comment]
Dear Gautier,
Any news about this feature? I was going to try to code it myself but I wanted to check if you had been looking into it in case of :)

**Comment by gtrichard** [comment]
Err sadly not yet :(

It's on the to do list for sure though. If you want it quickly I guess the best is to code it yourself sorry :(

**Comment by samuelCollombet** [comment]
Dear Gautier,
I have made a version of hicAggregateContacts that take a --genome argument to average contacts on all the genome instead of per chromosome (also output genome-wide contacts in one tab file if --outFileContactPairs is given). Seems to work fine, but I haven't tested the clustering part (should work but not sure).
If you want to have a look at it let me know how to share it with would :)

**Comment by gtrichard** [comment]
Dear Samuel,

It is so nice of you thank you very much 😄 !

I would for sure gladly test it, as I was just about to need it for one of my (many) analyses! I think the best way would be to Fork the HiCExplorer repository, make a new branch from the develop one in your fork, add your feature in hicAggregateContacts and ask for a Pull request. Then we will try it, if everything is fine then we will accept the Pull request 😃 .

**Comment by LeilyR** [comment]
Hi Samuel, 
This link may save you some time:
https://guides.github.com/activities/forking/
