### ISSUE TITLE
Question about the output of hicPCA

### ISSUE THREAD

**Issue by QianzhaoJ** [deeptools/HiCExplorer#277]
Hi

To compute the A / B compartments ,I used hicPCA and get pca1.bedgraph , pca2.bedgraph. I'm very confused about the two bedgraph files . 
For example , In one bedgraph there is  chr1  520000  560000  0.0045540143 , but In the other there is chr1  520000  560000  -0.004626316597 . So how should I classify A / B compartments by opposite values ? 
Best

**Comment by vivekbhr** [comment]
PC1 is the one you are looking for.. (see my google group post)

**Comment by joachimwolff** [comment]
I have to add here some information: In the most cases you look for PC1 and positive values correlate to open chromatin and negative to closed. 
All rules come with exceptions: some times it is PC2 and not PC1. For details on this please see Lieberman-Aiden 2009, in this paper the issues with principal component analysis are well explained. Moreover, sometimes the sign of an principle component needs to be flipped to show the correct result. It depends on the version of numpy and from which source you have it. This is a bit an annoying behavior, and will be fixed in the next version of HiCExplorer. We will give you the option to flip the values of a PC by correlating it with the gene density. Until the version is released please be careful and have a look if the values have the correct sign. You can do this by e.g by a visual inspection and correlation with known factors for open / closed chromatin.

**Comment by QianzhaoJ** [comment]
It would be wonderful !
