### ISSUE TITLE
ImportError: No module named HiCMatrix

### ISSUE THREAD

**Issue by QianzhaoJ** [deeptools/HiCExplorer#335]
Congratulations for the release of HiCExplorer version 2.2 ! 
  But after I updated HiCExplorer by conda ,I found 
> Traceback (most recent call last):
  File "/data1/liuzunpeng/04_Softwares/anaconda/bin/hicPlotTADs", line 4, in <module>
    from hicexplorer.hicPlotTADs import main
  File "/data1/liuzunpeng/04_Softwares/anaconda/lib/python2.7/site-packages/hicexplorer/hicPlotTADs.py", line 4, in <module>
    from pygenometracks import plotTracks
  File "/data1/liuzunpeng/04_Softwares/anaconda/lib/python2.7/site-packages/pygenometracks/plotTracks.py", line 152, in <module>
    import pygenometracks.tracksClass
  File "/data1/liuzunpeng/04_Softwares/anaconda/lib/python2.7/site-packages/pygenometracks/tracksClass.py", line 26, in <module>
    import hicexplorer.HiCMatrix as HiCMatrix
ImportError: No module named HiCMatrix

when I used **hicPlotTADs**.
    I saw that you have restructured the  HiCMatrix to object oriented model and moved to its own library: deeptools/HiCMatrix ,but I found `import hicexplorer.HiCMatrix as HiCMatrix` in **tracksClass.py** ,line 26 . When I changed it to `from hicmatrix import HiCMatrix` , the error disappeared .
  So ,Perhaps you should check this script?
Thanks !
Qianzhao

**Comment by joachimwolff** [comment]
Hi Qianzhao, 

thanks for the feedback.

This error looks like it is caused by a not correct installed HiCExplorer and its dependencies. The error you mention is impossible to raise with the up-to-date version of pyGenomeTracks which is 2.1. Can you please check if the used version is really 2.1? I guess you have somehow maybe two version of pyGenomeTracks installed. 
To fix this I usually do: 
`pip uninstall pygenometracks` and I repeat this as long as it does not find any version anymore. 
In the next step I would recommend to use conda environments:
`conda create --name hicexplorer22 python=3.6 hicexplorer=2.2`
and do `source activate hicexplorer22` to use it.
I hope this will help you and solves your issues.

Best,

Joachim

**Comment by QianzhaoJ** [comment]
Indeed ,when 'pyGenomeTracks  --version', I found  it is in **2.0** .
I will creat a new env for hicexplorer
Thanks a lot !
Qianzhao

**Comment by MzwaneleN** [comment]
I am trying to run hicNormalize and i get the following error:

(ENV) [name@server scratch]$ hicNormalize -m 5kb_converted_matrix.h5 5kb_converted_matrix.h5 --normalize smallest -o norm_5kb_converted_matrix norm_5kb_converted_matrix.h5
Traceback (most recent call last):
  File "/home/mngubo/ENV/bin/hicNormalize", line 4, in <module>
    from hicexplorer.hicNormalize import main
  File "/home/mngubo/ENV/lib/python3.6/site-packages/hicexplorer/hicNormalize.py", line 6, in <module>
    from hicmatrix import HiCMatrix as hm
ModuleNotFoundError: No module named 'hicmatrix'

**Comment by LeilyR** [comment]
Please install hicMatrix. It is one of the required tools. If you use conda for the installation, it will take care of all the requirements.
