### ISSUE TITLE
parameters for star aligner

### ISSUE THREAD

**Issue by abhisheksinghnl** [deeptools/HiCExplorer#337]
Hi,

I have a question regarding the mapping of genome and the chimeric reads. Kindly find time to help me.

So in the manual of Hi-C explorer, you have suggested to use BWA, I have plant genome and the size of the genome takes very long to map because of which I shifted to STAR aligner with following parameters:-

--alignIntronMax 1 --alignIntronMin 2 --outFilterMultimapNmax 1 --runThreadN 8 -- --alignEndsType local (default)

Now my question is, what more parameters can I add or optimize the present ones, so that chimeric reads are not compromised.

Second question is, can I use the aligned file from STAR with Hi-C explorer tools? I guess,yes.

Many thanks in advance.

Best regards

**Comment by gtrichard** [comment]
Hello abhisheksinghnl and thanks for considering using HiCExplorer.

As a rule of thumb and as you noted, we always use BWA for Hi-C reads mapping. Other tools are using other aligners like Bowtie. By searching a bit I found that HIPPIE is using STAR for Hi-C mapping with the following parameters:

```
$STAR \
 --runThreadN 1 \
 --genomeDir "${REF_FASTA}" \
 --readFilesCommand zcat \
 --readFilesIn "${fastq_file}" \
 --outSAMattributes All \
 --outSAMunmapped Within \
 --outSAMtype BAM Unsorted\
 --outReadsUnmapped Fastx \
 --outFileNamePrefix "${sam_file_prefix}" \
 --outFilterMultimapNmax 1   \
 --outFilterMismatchNoverLmax 0.04 \
 --scoreGapNoncan 0  --scoreGapGCAG 0  --scoreGapATAC 0 \
 --alignIntronMax 1 \
 --chimSegmentMin ${ChimSegMin} \
 --chimScoreJunctionNonGTAG 0 \
 --genomeLoad LoadAndKeep 
```

Source: https://github.com/yihchii/hippie/blob/master/cmd/starMappingToBam.sh

One of the problem is that they say that "# thread has to be 1 to keep the read order", so I'm not sure that STAR with 1 CPU will be much faster than BWA with plenty. They are doing this to keep the same reads order between the two mapped files (R1 and R2) in order to pair them easily. Of course this is not the right solution as then the alignment takes ages to run.

As an alternative, Bowtie2 can be used. Again, I don't know if it will be faster than BWA. The Mirny Lab is using Bowtie2 to map Hi-C reads:

https://mirnylab.bitbucket.io/hiclib/mapping.html

Now back to STAR. Yes, it could be used to map Hi-C reads as long as you map each pair individually and prohibit splicing with the following parameters:
`--alignIntronMax 1 --alignMatesGapMax <MaxInsertSize-2*ReadLength>`

You could also check the options concerning the chimeric reads in STAR manual.

After the mapping, be sure to reorder the reads of the two individually mapped files so read order is matching, using for example Picard ReorderSam:
https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.5.2/picard_sam_ReorderSam.php

**Comment by LeilyR** [comment]
I suppose Bowtie2 is faster, though cannot confirm the best combination of parameters to use. 

Regarding to bwa command you have sent, -U needs an int as the penalty which you havent mentioned, and I dont think it is needed, so I would have removed it.  Another thing you  need to add is -t to run it with multi-threads otherwise it is gonna take so long.
