### ISSUE TITLE
Question about --range argument for hicCorrelate 

### ISSUE THREAD

**Issue by kalavattam** [deeptools/HiCExplorer#348]
Hi all,

Can you provide a little more background info for the `hicCorrelate` optional parameter `--range`?

So, for example, let's say a user wants to plot the correlation between two technical replicates from some human samples. Each rep is from a 4-cutter and was sequenced on a Illumina HiSeq 2500 lane, maybe 75-bp PE reads, and has been aligned and processed but not yet normalized via ICE, KR, etc. Each rep comprises ~175M valid Hi-C contacts and each has approximate max resolutions of ~25-40 kb (i.e., binning such that all bins have Hi-C contacts). What do you advise to set `--range` to (if you advise to set it at all)?

Thanks,
Kris

**Comment by gtrichard** [comment]
`--range` might be useful after comparing the `hicPlotDistVsCounts` curves form multiple samples to determine a correct range of contacts.

`hicCorrelate` on the whole range might yield not-so-informative correlations, like you would get from comparing genome-wide ChIP-seq bedgraphs instead of peaks for example.

**Comment by kalavattam** [comment]
Thanks so much, Richard! Your explanation helps to contextualize these QC analyses.

Also, HiCExplorer is great--keep up the great work.
