### ISSUE TITLE
Very low percentage of pair used 

### ISSUE THREAD

**Issue by abhisheksinghnl** [deeptools/HiCExplorer#361]
Hi,

![DiscardedTable](https://user-images.githubusercontent.com/20971751/54520813-d7a7c180-4969-11e9-8180-386f2378a9a1.PNG)
![UnmappedTable](https://user-images.githubusercontent.com/20971751/54520814-d7a7c180-4969-11e9-96d5-cbd412a503a2.PNG)
I have mapped and build hicmatrix as suggested in the manual and when I run the qc I get very low percentage of pair used.

I was just wondering what could be the possible reason for this.

Is it because of the chimeric reads that are also being treated as PCR duplicates or something else technical that is leading to this large number of unmapped reads or low percentage of mapped reads?

Please help as I need to explain this to my fellow wet lab guys. They strongly believe that it is more of a computational thing while I believe it is more of experimental mix up.

Please find the table in the attachment.

Thank you

**Comment by gtrichard** [comment]
Which command-line did you use to build the matrices and do the QC please?

0% dangling end is extremely weird.

**Comment by abhisheksinghnl** [comment]
Hi,

here is the buildhicmatrix command

` hicBuildMatrix --samFiles log9.bam log10.bam --QCfolder hicU2 -bs 25000 --outBam U2.bam --minDistance 300 --maxLibraryInsertSize 1000 --restrictionSequence GATC  --outFileName Matrix.HiC.U2.cool --minMappingQuality 5 --skipDuplicationCheck --threads 8 -ze hicU2.err -zmem 700G -zslot 8 -za`

and for QC

`hicQC --logfiles /hicT1/QC.log /hicT2/QC.log /hicU1/QC.log /hicU2/QC.log --labels "T1" "T2" "U1" "U2" --outputFolder QC_all_samples`

**Comment by gtrichard** [comment]
Please try the following:

```
hicBuildMatrix --samFiles log9.bam log10.bam --QCfolder hicU2 --outBam U2.bam --restrictionSequence GATC --restrictionCutFile GATC.bed --outFileName Matrix.HiC.U2.cool --skipDuplicationCheck --threads 8 -ze hicU2.err -zmem 700G -zslot 8 -za

hicQC --logfiles /hicT1/QC.log /hicT2/QC.log /hicU1/QC.log /hicU2/QC.log --labels "T1" "T2" "U1" "U2" --outputFolder QC_all_samples
```

**Comment by abhisheksinghnl** [comment]
Hi,

Thanks for the edit in the command. i will try it and get back to you.

For the second one yes the RE is DpnII.

Fingers crossed.

**Comment by abhisheksinghnl** [comment]
> 
> 
> Please try the following:
> 
> ```
> hicBuildMatrix --samFiles log9.bam log10.bam --QCfolder hicU2 --outBam U2.bam --restrictionSequence GATC --restrictionCutFile GATC.bed --outFileName Matrix.HiC.U2.cool --skipDuplicationCheck --threads 8 -ze hicU2.err -zmem 700G -zslot 8 -za
> 
> hicQC --logfiles /hicT1/QC.log /hicT2/QC.log /hicU1/QC.log /hicU2/QC.log --labels "T1" "T2" "U1" "U2" --outputFolder QC_all_samples
> ```
> 
> To get GATC.bed please use `findResSites`
> https://hicexplorer.readthedocs.io/en/latest/content/tools/findRestSite.html#findrestsite
> 
> By the way, GATC is the correct sequence recognised by the restriction enzyme used in the protocol right (DpnII)?
> 
> Usually the fraction of pairs used is 0.50 (50%).

Hi,

Without giving the bin size I run into memory issues. Even 700Gb was not enough :(

**Comment by gtrichard** [comment]
Can you try to split the bam files in half, just for the sake of testing?

**Comment by abhisheksinghnl** [comment]
Hi,

I used the following command and increased the memory top 1000GB 

`hicBuildMatrix --samFiles log1.bam log2.bam --QCfolder hicT1 --outBam T1.bam --restrictionSequence GATC --restrictionCutFile rest_site_positions.bed --outFileName New.Matrix.HiC.T1.cool --threads 8`

I got following error at the end

```
INFO:hicmatrix.HiCMatrix:Only init object, no matrix given.
Traceback (most recent call last):
  File "/tools/eb/software/Miniconda3/4.4.10/envs/hicexplorer_new/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/tools/eb/software/Miniconda3/4.4.10/envs/hicexplorer_new/lib/python3.6/site-packages/hicexplorer/hicBuildMatrix.py", line 1381, in main
    if args.outFileName.name.endswith('.cool') and args.binSize is not None and len(args.binSize) > 2:
TypeError: object of type 'int' has no len()

```

what does this indicates and how can I resolve it.

Please guide.

Thank you.

**Comment by joachimwolff** [comment]
Hi,

you can decrease the number of used cores to 4 - 6, if I/O is not really fast there will no benefit and will waste memory. Moreover, to speed up the processing time and save memory, don't use the `--outBam` parameter. 

The error you get is caused by a bug from our side. I will try to provide a patched version today. However, if you don't want to wait, you can run, as you did in the beginning, with a fixed binSize resolution instead restriction enzyme cut level.

Best,

Joachim

**Comment by abhisheksinghnl** [comment]
Hi Joachim,

thank's for the explanation. 

The primary question still remains unanswered and that is what could be the reason for having such a small percentage if used pairs?

Could you please give a guess.

Best regards
Abhishek

**Comment by abhisheksinghnl** [comment]
> 
> 
> Hi,
> 
> you can decrease the number of used cores to 4 - 6, if I/O is not really fast there will be no benefit and it will waste memory. Moreover, to speed up the processing time and save memory, don't use the `--outBam` parameter.
> 
> The error you get is caused by a bug from our side. I will try to provide a patched version today. However, if you don't want to wait, you can run, as you did in the beginning, with a fixed binSize resolution instead restriction enzyme cut level.
> 
> Best,
> 
> Joachim

Hi Joachim,

thank's for the explanation.

The primary question still remains unanswered and that is what could be the reason for having such a small percentage if used pairs? Is it because of the chimeric reads also being treated as PCR duplicates and being discarded? If yes, how can I fix it?

Could you please give a guess.

Best regards
Abhishek

**Comment by gtrichard** [comment]
I think it is more than in a lot of read pairs, the restriction enzyme site cannot be detected, explaining while you have a lot of "same fragment" (meaning you read pair is only composed of 1 locus in the genome instead of 2 loci).

You also have a lot of low quality reads, I think it has to do with your MAPQ threshold.

You also have a lot of multimapped reads, which is a problem since HiCExlorer is only keeping single mapped reads.

**Comment by abhisheksinghnl** [comment]
> 
> 
> I think it is more than in a lot of read pairs, the restriction enzyme site cannot be detected, explaining while you have a lot of "same fragment" (meaning you read pair is only composed of 1 locus in the genome instead of 2 loci).
> 
> You also have a lot of low quality reads, I think it has to do with your MAPQ threshold.
> 
> You also have a lot of multimapped reads, which is a problem since HiCExlorer is only keeping single mapped reads.
> 
> If you take already published fastq files and apply the same command-lines, what do you obtain?

Hi Richard,

thank you for your reply.

Okay, here is my plan and I need your help for second part.

1.  I will modify the --minMappingQuality from 5 to 15.

2. How can I allow multimapped reads?

**Comment by joachimwolff** [comment]
Hi,

after some discussions in our team: 
 
- T1 vs the other samples shows significant difference. For us it looks like you used different parameter settings for mapping. Please redo the mapping.
- Plants can have highly repetitive regions, we are unsure if this is a normal artifact, you did some mistake in the mapping or your data is having errors.
- It is not possible to allow multi mapped reads with HiCExplorer. The reason is that we don't know to which region a read should belong to. It is maybe again some mappers issue. Please try different mapper settings to decrease the amount of multi-mapped reads.

Best,

Joachim

**Comment by joachimwolff** [comment]
> Is it because of the chimeric reads being treated as PCR duplicates or multimapping of reads ? If yes, how can I fix it?

The whole Hi-C method works only because of chimeric reads. We consider something as PCR duplicate as soon as two reads map to the identical position which is quite unlikely to happen. The classification of a multimapped read is not done by HiCExplorer it is a decision from your mapper. We think the mapping step is the one which goes wrong or the data contains errors and is of bad quality. 
 
The second big issue in T2, U1 and U2 is 'same_fragment': We consider one chimeric read as one fragment if their mapped position differs less than `maxLibrarySize`, which you set to 1000 base pairs and is our suggestion. We don't know why you have that many reads which are more or less non-chimeric. We strongly recommend to test other, already published data from the same organizm with HiCExplorer to figure out if the error is caused by HiCExplorer, the data from a genome like yours behaves this way or something went wrong creating this data.

**Comment by abhisheksinghnl** [comment]
Hi Joachim,

Just to make it clear, I have used following parameters for alignment using
bwa mem:

*bwa mem -A1 -B4  -E50 -L0*

Would you suggest any additional parameters or tweak in the present ones?

Thank you

**Comment by joachimwolff** [comment]
Hi Abhishek,

please try different mappers like bowtie or hisat and use their `--reorder` parameter. I don't have experience with plant genomes, maybe you need to adjust there the parameters. I don't know how good the three from us tested mappers (bowtie, hisat and BWA) are for plant genomes, maybe they don't work at all for them, or there is something special you need to have in mind for creating the reference genome. Please check also all the trivial issues: correct reference genome version, single-end mapping, fastqc report.

My apologies I cannot help you here more. 

Best,

Joachim

**Comment by joachimwolff** [comment]
After some more discussions: Can you map the reads, write all non-unique reads to a file and investigate these via IGV? There should also be the option in the mapper to remove the non-unique reads.

**Comment by abhisheksinghnl** [comment]
Hi Joachim,

Thank you for your email.

I will give it a try.

Presently, I am trying the mHiC https://github.com/yezhengSTAT/mHiC

have a look at the way author using bwa to map reads. May be that will make
the difference.

Do give your inputs.

Best regards
Abhishek

**Comment by abhisheksinghnl** [comment]
Hi Joachim,

I did figure it out, what might be happening.

Is it possible to change the definition of "informative reads", for example
if it was between 2kb to 10kb on same chromosome to all distances higher
than 2kb on the same chromosome?

How and at which step I can edit this?

Best regards
Abhishek

**Comment by jakevc** [comment]
I am also struggling to understand why some experiments are returning very low "pairs used", I pipeline hicExplorer with snakemake so it's fairly reproducible. First the data are aligned using bowtie2, the only non-default parameter being `--reorder`. Then, here is my build matrix rule:

```
rule build_matrix:
    input:
        "data/aligned/{sample}_R1.bam",  "data/aligned/{sample}_R2.bam"
    output:
        "data/buildMatrix/{sample}_10kb.h5"
    conda:
        "envs/hic.yml"
    threads: 16
    shell:
        "hicBuildMatrix --samFiles {input[0]} {input[1]} "
            "-bs 10000 "
            "--outBam data/buildMatrix/{wildcards.sample}_ref.bam "
            "--outFileName {output} "
            "--QCfolder data/buildMatrix/{wildcards.sample}_QC "
            "--threads {threads} "
            "--inputBufferSize 500000"
```

With the above code I have run on a number of datasets. The dataset from  Rao et al. 2014 having the highest number of "pairs used". 

Best case: 

![hicexplorer_categorization_plot](https://user-images.githubusercontent.com/17414791/55824087-007a2d00-5ab8-11e9-90e3-27305820e2c7.png)

Worst case:

![hicexplorer_categorization_plot (1)](https://user-images.githubusercontent.com/17414791/55826468-f27adb00-5abc-11e9-8ad8-824d78c20223.png)

**Comment by LeilyR** [comment]
You might need to check your mapping parameters. You need to set a high gap penalty and no clipping penalty. In fact, we already have a HiC snakemake pipeline which you might be interested in running your data using that and compare the results with yours. You can find it here: `https://github.com/maxplanck-ie/snakepipes.git`. We used `bwa mem` though and we also mapped each mate of a paired end reads separately since the mates may come from distant regions on a genome.

**Comment by joachimwolff** [comment]
Please post the exact files you used. It is for us really difficult to understand if your dataset is maybe bad or there is an issue with HiCExplorer.
