### ISSUE TITLE
Acquiring interactions from the Hi-C Matrix

### ISSUE THREAD

**Issue by abhisheksinghnl** [deeptools/HiCExplorer#379]
Hi,

I have build my interaction matrix and now I want to get the interactions out of this matrix.

How can I do this?

I have performed LoopDetection calling and I got some loops. Is this all I can do or something more I can do to get the interaction of the regions that might have gone undetected during Loop detection step.

Thank you

**Comment by gtrichard** [comment]
You can use `hicConvertFormat` to export a h5 or cool file to GInteractions format. This will give you ALL interactions as a bed-like file.

Loop detection gives you the meaningful interactions in a validated manner. If you want to see long range contacts between specific regions, it is better to use `hicAggregateContacts`

**Comment by abhisheksinghnl** [comment]
Hi,

Thank you for your reply. I got a file in this format:

```
chr1B   487650000       487675000       chr1B   502625000       502650000       2
chr1B   487650000       487675000       chr1B   502775000       502800000       1
chr1B   487650000       487675000       chr1B   502875000       502900000       1
```
Just to confirm, the first three columns are the starting co-ordinate of the interaction site and the column no. 4-6 are the interaction site, what is the last column representing?

**Comment by gtrichard** [comment]
The first three column = bin1
The second three column = bin2
Last column = number of interactions, i.e. the number of read pairs corresponding to bin1 and bin2.

A "good number" is very hard to define... It will highly depend on the distance between bin1 and bin2 of course. This is not a trivial question.

If you want to see if some interactions are enriched against background, you need a proper way to do it. HiCExplorer is beginning to support such approaches and it boils down to loop-calling. The problem is that is depends on your genome mostly... For mammalian genomes I think it is not an issue, for anything else it can be problematic.

If you have an a priori on the regions you want to check (are they close in space / clustering in space?), you can use `hicAggregateContacts`.
