### ISSUE TITLE
problem about hicPCA input file format 

### ISSUE THREAD

**Issue by qianXX** [deeptools/HiCExplorer#448]
Hi!

For plotPCA function, I have some problems.

I wasn't able to clearly understand this input format of gene track file. In fact, no matter whether I use the bigwig file of gene density or the bed file of the genes, I still can't run it successfully.

Is this related to the version of the software I am using? Use "--version" parameter, I found that the plotPCA version I used was 2.2.1.1.

**Comment by LeilyR** [comment]
By the way what did you really mean by plotPCA? there is no such a tool in hicexplorer. did you mean hicPCA or something else?

**Comment by qianXX** [comment]
Sorry about this, here I mean hicPCA. 
For some network reasons, I am unable to successfully download the latest version.
I will give you feedback about the software version when I get new version software.

**Comment by joachimwolff** [comment]
If you used 2.2 before, it could be possible you still use Python 2.7 and / or use pip as package manger. We dropped the support for both, please use Python 3.6 and conda package manger.

**Comment by LeilyR** [comment]
I have tested hicPCA 3.3 with a bigwig file (a histon mark coverage file) and I couldnt generate any error and it ran successfully. 
Just one point to mention, you shouldn't run hicPCA on a very high resolution matrix. It gets computationally expensive and it doesnt make so much sense biologically either since you are looking to find large active/inactive regions.

**Comment by LeilyR** [comment]
@qianXX We assume that your problem has been solved since we have not heard of you anymore. I close this issue now, bet us know if there is still any question left.
