### ISSUE TITLE
Use HiCExplorer to dump data with options directly

### ISSUE THREAD

**Issue by Linhua-Sun** [deeptools/HiCExplorer#451]
Hi: 
    I have a small suggestion. Can HiCExplorer support export or dump data to stdout or plain text directly? Similar to `cooler dump` (https://cooler.readthedocs.io/en/latest/cli.html#cooler-dump). And can also specify options like regions, correction value.
    Similar issue is also in `hicPlotMatrix`. Can `hicPlotMatrix` add an option to export data accompanying the figure similar `hicPlotDistVsCounts`'s option`--outFileData`.
Because, at present, we have to use `hicConvertFormat` to convert data in h5 into cooler format or others and use cooler to dump. It will be useful to check the data and use other ways like R to handle the data. And all things can be done a single h5 environment.
Thanks.
Linhua Sun

**Comment by joachimwolff** [comment]
Hi Linhua,

what we have is the option in hicConvertFormat to write out a homer or GInteractions file. These are both text formats which can be inspected manually. However, I would recommend to limit it first to the region your are interest in with hicAdjustMatrix before. The outputs can be really large and it is time consuming to write out these text files.

hicPlotMatrix does not have the --outFileData option because we use the data which is stored in the matrix and no computations (except the log) is applied.

Best,

Joachim

**Comment by Linhua-Sun** [comment]
Thank you for your reply. Great job about HiCExplorer !
