### ISSUE TITLE
Question about HiCcorrelate

### ISSUE THREAD

**Issue by EnrichettaMileti** [deeptools/HiCExplorer#463]
Hi. How we should set range parameter in correlate? I'm working with mouse and human data and  as far as I understood this parameter will influence the correlation analysis

**Comment by LeilyR** [comment]
--range in hicCorrelate does that.

**Comment by EnrichettaMileti** [comment]
Yes this I understood. But how we should set it up?

**Comment by gtrichard** [comment]
Dear EnrichettaMileti,

The best way to get a grasp on the --range you have to set is to make hicPlotDistVsCounts plots with the different samples. You should be able to spot ranges where samples are different and ranges where they should correlate.

I usually prefer these hicPlotDistVsCounts representations alongside the QCs rather than hicCorrelate to get an idea of how correlated the samples are.

All the best,
Gautier
