### ISSUE TITLE
How to interpret the output plot of hicCompartmentsPolarization?

### ISSUE THREAD

**Issue by ykai16** [deeptools/HiCExplorer#473]
Hi, 

Could you provide some guidance on the interpretation of the output plot of hicCompartmentsPolarization? Here I attached an example below. Thanks!

![Picture1](https://user-images.githubusercontent.com/16323164/71049204-b39f2980-210f-11ea-916d-1efd72e73045.png)

**Comment by LeilyR** [comment]
Hi,
I shows how well your active/inactive compartments have been formed. The y axes presents:
`(interaction within act. compartment + interaction within inact. compartment)/interaction between act. and inact. compartments` while the x axes shows the number of bins. If you get values `>1` it means that the interaction within the compartments were higher than between them, so you had some compartment separation and the higher it goes means the stronger they got formed. For that matter horizontal dashed line = 1 and the vertical line shows the middle of your matrix (half of the bins)
Also, I suggest you the use this module from fix_polarization branch for now, since we have fixed some bugs there. These changes will be added to our next release.

**Comment by LeilyR** [comment]
I close this issue but don't hesitate to get back to us if you still have any issue understanding the output. Also, bear in mind that this module soon will be renamed to hicCompartmentalization.

**Comment by ykai16** [comment]
Thanks a lot for the explanation and suggestion! 

One question is that what does the "Quantiles" of the x-axis mean exactly in the calculation?  For example, if 30 was used for the quantile number, how to select the regions in A and B compartments to calculate the signal (i.e what's shown in y axis) at the first quantile? A detailed explanation would be very helpful for us to interpret the result, thanks for the help!

**Comment by LeilyR** [comment]
the number of quantiles is a user defined value which tells the tool how to partition the pc1 values to that number. It also defines the number of bins on a matrix which later on will be built over obs/exp interactions considering this partitioning of pc1 values. So the figure above is basically presenting that matrix which its shape is number_of_quantiles*number_of_quantiles. 
Y axis is presenting values which come from counting 2 corners of this matrix which are supposed to contain A and B bins (starts with the first bin only) and dividing that value to sum of values of two other corners.  The size of corners expands one bin at the time so the further you go on the x axis the closer you get to the center of matrix until the vertical dash line which show the center. The expansion keeps happening though until the last bin is covered. Why this? because if you have a clear separation of A and B compartments the sum of those 2 corners should be significantly higher than the 2 other corner of the matrix so the ratio should be well above 1. this ratio decrease when the number of bins considered for that corner increase. The later it reaches 1 means the larger your compartments are. (The horizontal dashed line shows 1)

**Comment by GregZs** [comment]
Hi,
I am using hicexplorer 3.6 and I am trying to use the hiccompartmentalization tool:
hicCompartmentalization --obsexp_matrices hic_OE_adj_res100000.h5 --pca pca1.bedgraph -o global_signal.png --outputMatrix output_cs
Here is the output that I obtained:
![global_signal 2](https://user-images.githubusercontent.com/49447516/100254619-d43c4a00-2f42-11eb-8406-042df632423f.png)

Does the x-axis represents the bins ordered from the A compartment on the left to the B compartment on the right ?

Because I tried to sort the pca1.bedgraph according to the pca scores and then run again hicCompartmentalization and I obtained a different output:
![global_signal](https://user-images.githubusercontent.com/49447516/100255307-a4da0d00-2f43-11eb-856e-e8c4d6cbd0bf.png)

Also I tried to plot the output matrix to obtain a saddle plot but the values do not correspond 
![Unknown](https://user-images.githubusercontent.com/49447516/100255452-ccc97080-2f43-11eb-9c8b-605f9f363745.png)

Can the tool be run genome wide or it has to be done by chromosome ?
Why sorting the bedgraph by the pca score changes the output ?
How can I get the values used for the plot from the npz object ?

Thanks in advance

**Comment by 14stutzmanav** [comment]
Hi there,

I have a question related to this: When I look at the output of these plots, there is a bin "0", leaving us with 31 total bins instead of 30 total bins. Can you please explain bin 0?

Thanks so much!
