### ISSUE TITLE
Question about Normalization

### ISSUE THREAD

**Issue by C-L-Wike** [deeptools/HiCExplorer#490]
can you help clarify the best method for normalization. 
I have two samples with relatively similar sequencing reads. however the actual valid pairs used is drastically different. 

would it be better to normalize using the normalization range 0-1 method or to normalize to the smallest read count. 

Could you further clarify if the normalization option smallest read count is based on total reads sequenced or valid read pairs used for building the HiC matrix. 

Alternatively, considering I have a significant difference in valid read pairs  between my samples would it be better to downsample the valid bam pairs file so that they are equal between my sample and then recreate matrices with the same valid pairs count? 

thank you for taking your time!

**Comment by gtrichard** [comment]
Hello,

> would it be better to normalize using the normalization range 0-1 method or to normalize to the smallest read count.

The best is to use `--smallest`, as the 0 to 1 range may fail with some of our tools (it can be useful to export the matrix to other softwares that need that 0 to 1 range, but within HiCExplorer, use `--smallest`).

> Could you further clarify if the normalization option smallest read count is based on total reads sequenced or valid read pairs used for building the HiC matrix.

The normalization `--smallest` is using the sum of contacts stored in the matrix, i.e. what is displayed with `hicInfo`.

It is better to use `hicNormalize` on uncorrected matrices (and correct them afterwards using `hicCorrectMatrix` KR correction).

> considering I have a significant difference in valid read pairs between my samples would it be better to downsample the valid bam pairs file

Please define significant. From experience, I saw an advantage of using down-sampling when you have at least 2 times more contacts in one sample vs the other. For the record, it was linked to a differential number of X chromosomes between males and females, 2X females vs 1X in males, i.e. two times less contacts in males on that chromosome. This required a down-sampling of the female Hi-C specifically on the X chromosome. Using solely `hicNormalize` in that case, even on the X chromosome only, yielded weird outputs in `hicAggregateContacts`, mainly because of the difference of sparsity of the matrices.

**Comment by C-L-Wike** [comment]
Awesome! thanks for the response it was very helpful
