### ISSUE TITLE
hicPlotTADs shows strange chr1 boundary

### ISSUE THREAD

**Issue by sshen82** [deeptools/HiCExplorer#528]
Hi,
I was trying to use hicPlotTADs to plot the chr1 from 0 to 30mb, but 0-4mb of this is very strange. This part should be zero (as is shown in the second plot), but the color indicates that there are very large values. 

![hic_track](https://user-images.githubusercontent.com/29969832/78795149-45120000-797a-11ea-9190-dc59bca93eb9.png)

![matrix](https://user-images.githubusercontent.com/29969832/78795163-493e1d80-797a-11ea-9aed-02ddfdf21f99.png)

**Comment by joachimwolff** [comment]
Hi,

The mentioned regions could be masked by 'nan' values and are not 0. What we do in the plotting is to 'extend' the surrounding regions to this region to have a nicer plot. In your very special case: Simply restrict the start of your region to 4.8 Mb - 4.9 Mb because you don't have there no TADs anyway.

Best,

Joachim

**Comment by sshen82** [comment]
I see, thanks for your help!
