### ISSUE TITLE
Problem about hicPCA _ more like suggestion/discussion

### ISSUE THREAD

**Issue by zyqfrog10** [deeptools/HiCExplorer#529]
Hi @gtrichard @joachimwolff ,

I have observed the similar behavior of hicPCA as described in https://github.com/deeptools/HiCExplorer/issues/346

As suggested, I masked the centromere. Most of the chromosomes look fine for human genome except  chr13, chr15, and chr22 (shown as below).  

<img width="961" alt="chr22_AB" src="https://user-images.githubusercontent.com/9779738/79002575-bdb1c180-7b1e-11ea-891b-5c85f3546c9b.png">

These three chromosomes' PC1 all look alike. And they all have short arm with sparse or no genes. PC2 looks workable for these three chromosomes. For these three chromosomes, PC1 represents chromosome arms while PC2 fits the A/B compartment as advised by @joachimwolff  

@gtrichard questioned why this is hicPCA specific, not in other tools. 
When I looked at the above tracks, I start to think it might be related to how hicPCA handle zero count regions on the genome in the matrix. I am wondering if hicPCA can remove zero count regions internally, would the PC1 improve?

Thanks.

-YZ

**Comment by joachimwolff** [comment]
Please have a look at Lieberman-Aiden 2009 publication „Comprehensive mapping of long-range interactions reveals folding principles of the human genome“. This is the very first publication about Hi-C and contains the way we compute A/B compartments. In this publication the same effect is already described. This effect that you see is caused by the eigenvector decomposition, and happens always in all tools. It has something to do with the properties of the matrix and which components are orthogonal to each other. Maybe others hide it better than we do, you can e.g. correlate all PC with the gene density, we use this only to flip the values. However, if you use the same to detect which A/B compartments are best correlated you can hide it. I think this is mathematically wrong, and it is better to present the user not a wrong order of the PCs.

Best,

Joachim

**Comment by zyqfrog10** [comment]
Thank you for your quick reply.
I am not sure whether it is fair to say others are trying to hide it. I cannot say for HiTC、cooltools explored in #346. But looks like Erez himself has adopted a way that drop the regions where no counts have been identified. As seen in chr13, chr15 and chr22, short arms have no eigenvalues from juicebox. I am just thinking it might be a way to avoid chromosome arm assignment in PC1.

![image](https://user-images.githubusercontent.com/9779738/79011234-9a444200-7b31-11ea-97be-7f8eb62a25e4.png)


![image](https://user-images.githubusercontent.com/9779738/79011448-09ba3180-7b32-11ea-8ecf-ea897dc4554c.png)

**Comment by joachimwolff** [comment]
Thank you for your input and we will consider it in a future update.
