### ISSUE TITLE
hicPlotDistVsCounts - straight line

### ISSUE THREAD

**Issue by ZhangJiankun21** [deeptools/HiCExplorer#534]
Hi,
I got the contact probability decay plot using hicPlotDistVsCounts. But there was a short straight line at the beginning of the curve. Is there anything wrong? (OUTFILEDATA seems OK.)

Thanks!

![image](https://user-images.githubusercontent.com/37240939/80710829-f7745780-8b21-11ea-9292-52532df5cb2f.png)

**Comment by gtrichard** [comment]
Dear @ZhangJiankun21 ,

This could be due to the resolution of the matrix (bin size). What is the bin size of the matrix used here ?

If you use a matrix with large bin size (for instance 100kb), then the first values will be equal (for instance 1kb, 50kb and 100kb), thus explaining the straight line.

**Comment by ZhangJiankun21** [comment]
Here the bin size is 50 kb. It makes sense to me. So I will just ignore these values. 
Thank you.
