### ISSUE TITLE
hicDetectLoops parameters - Drosophila

### ISSUE THREAD

**Issue by amv33576** [deeptools/HiCExplorer#535]
Hello, 
Given than the TADs in flies are way smaller than in humans or mice, and the interaction loops are also closer.  I am wondering if you have any recommendations for initial parameters to try on hicDetectLoops when working with Drosophila genomes?. 

Thanks!

**Comment by LeilyR** [comment]
@gtrichard have you tried this? Do you have any recommendation?

**Comment by joachimwolff** [comment]
Hi,

depending on your read coverage I would start with a peakInteractionThreshold of 1, and increase it slowly to 10 or 20. Maybe the -pp and -p Parameter to 0.1 at the beginning. With these you should get way too much loops, however, it is a good start point, all other parameters I would set them to default.

Best,

Joachim

**Comment by lubna290** [comment]
Hi,
I'm working on Drosophila genome and want to ask if its possible to plot the aggregate plot for loop interactions? Because for loops we want to see the interactions between two bins that are possibly way far from each other.

![Screenshot 2020-05-31 at 11 15 36](https://user-images.githubusercontent.com/64106867/83349610-813c5e00-a336-11ea-9a2f-8c8c4809c955.png)

Thanks
