### ISSUE TITLE
.h5 file size suggests matrix generation not working properly

### ISSUE THREAD

**Issue by dgoekbuget** [deeptools/HiCExplorer#557]
Hi,
Sorry if I am mistaken here, but I have two paired end bam files of 5.2Gb size (replicate 1) and  files of a mispooled sample of 8Mb size (replicate 2). These files were mapped according to your tutorial.
I generated .h5 matrices like this (using restrictions cut bed file from the company that sold the HiC kit):
`hicBuildMatrix --samFiles "$outfile"_1.bam "$outfile"_2.bam --restrictionCutFile "$restriction" --outBam "$outfile".bam --outFileName "$outfile"_10kb.h5 --QCfolder "$outfile"_10kb_QC --threads 24 --inputBufferSize 400000`
What I end up getting is .bam files of 2.8Gb and 3.6Mb size as expected (~26% of pairs used according to QC html), but strangely the .h5 matrix files are both 27Kb and 26Kb in size. 
Does this not mean sth is wrong?

**Comment by dgoekbuget** [comment]
Any suggestions?

**Comment by dgoekbuget** [comment]
Alternatively tried to generate .cool file, but got following error:

```
hicBuildMatrix -s ../bam/HiC.N2.dgrb06_1.bam ../bam/HiC.N2.dgrb06_2.bam -o HiC.N2.EtOH.dgrb06.cool --QCfolder ./qc -rs ../../genomes/mm10_GATC_GANTC.bed

INFO:numexpr.utils:Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:hicexplorer.hicBuildMatrix:reading ../bam/HiC.N2.EtOH.dgrb06_1.bam and ../bam/HiC.N2.EtOH.dgrb06_2.bam to build hic_matrix

INFO:hicexplorer.hicBuildMatrix:Minimum distance considered between restriction sites is 300
Max distance: 1000

INFO:hicexplorer.hicBuildMatrix:processing 22053490 lines took 1281.12 secs (17214.2 lines per second)

INFO:hicexplorer.hicBuildMatrix:5638364 (25.57%) valid pairs added to matrix

INFO:hicexplorer.hicBuildMatrix:processing 50027753 lines took 2733.91 secs (18299.0 lines per second)

INFO:hicexplorer.hicBuildMatrix:13040284 (26.07%) valid pairs added to matrix

Traceback (most recent call last):
  File "/home/goekbugetd/software/miniconda3/envs/hicexplorer/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/home/goekbugetd/software/miniconda3/envs/hicexplorer/lib/python3.6/site-packages/hicexplorer/hicBuildMatrix.py", line 1381, in main
    if args.outFileName.name.endswith('.cool') and args.binSize is not None and len(args.binSize) > 2:
TypeError: object of type 'int' has no len()
```

**Comment by joachimwolff** [comment]
Hi,

Yes there is definitely something wrong, the h5/cool file size should be in the MB range. 

Your error shows a bug, the check for `args.binSize is not None` is obviously not sufficient. We need to fix this, however, as a very first workaround: What happens if you don't use the restriction cut sites but a fixed bin size? I am mentioning this not only caused by the bug, but the resolution you choose here is the highest possible. Given you have only 5.2 GB input data implicates for me that you have by far not the read coverage to work in a useful way on the restriction cut site resolution.

Small side note: According to our own measures, we don't see any improvement of the runtime if more than 6 - 8 threads are used.


Best,

Joachim

**Comment by joachimwolff** [comment]
Hi,

after checking this error: You do not work with the current version of HiCExplorer. In the current version the line this error appears is in 1509, however, your error message shows it is line 1389. This leads to version 2.2.X.

Please install the current HiCExplorer version 3.4.3 and test if this error still appears.

Thanks a lot,

Joachim
