### ISSUE TITLE
Clarifying hicPCA

### ISSUE THREAD

**Issue by srcoulombe** [deeptools/HiCExplorer#578]
Hello!
First of all, I want to thank you for the time and energy you have all poured into HiCExplorer! What you've built has been very useful to me recently, and I've often referred to your repo to get a sense of how to organize large projects!
I just want to clarify a specific aspect of hicPCA: the 'expected' values used in the observed-vs-expected matrix are computed for the specific chromosome of interest yes? They aren't computed using all intra-chromosomal matrices?

**Comment by joachimwolff** [comment]
Hi,

all computations are computed per chromosome independently, therefore we consider only intra-chromosomal contacts for each chromosome, but no inter-chromosomal contacts. See: https://github.com/deeptools/HiCExplorer/blob/master/hicexplorer/hicPCA.py#L264 and the following lines.

Best,

Joachim

**Comment by srcoulombe** [comment]
Ok, thanks! In Lieberman's 2009 paper, they calculated the expected interaction for a genomic distance as the genome-wide mean interaction value. Did you guys find that this was inconsistent/problematic and that's why you chose to compute the expected interaction value in a chromosome-wise manner?

**Comment by LeilyR** [comment]
To compute PCA we compute the obs/exp chromosome wide, since we have noticed a big affect of noise coming from very small intr-chromosomal interaction values when computing the A/B compartments, especially on non-mammalian genomes.  However, if you are interested in having the obs/exp in a genome wide level, feel free to use hicTransform.

**Comment by srcoulombe** [comment]
Thanks for clarifying!
