### ISSUE TITLE
all_nan array dtype in hicCorrelation

### ISSUE THREAD

**Issue by brainfo** [deeptools/HiCExplorer#593]
my hicexploer is in v 3.5 and python in 3.7.8.
when using hicCorrelation on cooler files, it turns out that dtype of all_nan array is float instead of int/bool,  so the remove nan process cannot be done and the program will fail and exit.
I add a `all_nan = all_nan.astype(int)` then it will process well.
I do not know if this is a common issue so I wanna hear from you about this.

**Comment by joachimwolff** [comment]
Thanks for letting us now. We do not really understand why this bug appears now, at the release time of 3.5 this was working fine. We suspect something changed in our dependencies. However, we have registered this bug last week and it is already fixed in the dev version: https://github.com/deeptools/HiCExplorer/blob/develop/hicexplorer/hicCorrelate.py#L328

We will release soon a bug fix version 3.5.1.

Best,

Joachim
