### ISSUE TITLE
Latest version installation issues 

### ISSUE THREAD

**Issue by marizazh** [deeptools/HiCExplorer#632]
Hello hicexplorer team,

I have a couple of issues with hicexplorer which I’m trying to install with conda. I tried all possible options with conda supporting python 2.7 but then I don’t get tools version which supports hicDifferentialTAD which I’d like to run. Then I tested with different conda releases from 4.8.4 and now with 4.9.2. All that was done aiming finally get the lates version of HiCExplorer though all the time I was installing 2.2.1 version. If I’m trying install conda install hicexplorer=3.6 -c bioconda -c conda-forge, I’m getting tones of conflict messages and nothing is installed. So I started to play with conda channels settings and to be honest have no idea which combination helped to get hicexplorer 3.5.1!!! You cannot imagine how happy I was (after spending 2 days with installation) and obviously the first thing I tried was 

hicDifferentialTAD
Traceback (most recent call last):
  File "/Users/mzazhyts/miniconda3/bin/hicDifferentialTAD", line 7, in <module>
    main()
  File "/Users/mzazhyts/miniconda3/lib/python3.8/site-packages/hicexplorer/hicDifferentialTAD.py", line 260, in main
    domains_df = readDomainBoundaries(args.tadDomains)
  File "/Users/mzazhyts/miniconda3/lib/python3.8/site-packages/hicexplorer/hicDifferentialTAD.py", line 67, in readDomainBoundaries
    domains_df = pd.read_csv(pFile, sep='\t', header=None)[[0, 1, 2, 3, 4, 5]]
  File "/Users/mzazhyts/miniconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/mzazhyts/miniconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 430, in _read
    fp_or_buf, _, compression, should_close = get_filepath_or_buffer(
  File "/Users/mzazhyts/miniconda3/lib/python3.8/site-packages/pandas/io/common.py", line 200, in get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType’>

Can you please help with this matter? Any suggestions to get optimal conda channels settings? How to get tools version with working hicDifferentialTAD?

Thanks a million,
Marianna

**Comment by LeilyR** [comment]
hicexplorer does not support python2

**Comment by joachimwolff** [comment]
Hi,

long story short: Starting with HiCExplorer version 3.0 we do not support Python 2.7 anymore (since ~1.5 years). This information is provided for example: https://github.com/deeptools/HiCExplorer#installation , https://hicexplorer.readthedocs.io/en/latest/content/News.html#release-3-0 or https://hicexplorer.readthedocs.io/en/latest/content/installation.html#requirements

However, if you use already conda simply use a conda environment to get a Python 3.6, 3.7 or 3.8 version. This will be independent from the rest of your software and will not influence any Python 2.7 packages. Anyway, I can see that you are using a Python 3.8 installation and not the mentioned Python 2.7?! In your case it seems the root environment has already some packages, better clean this before you try the later described method:

```
conda uninstall hicexplorer hicmatrix pygenometracks
conda clean --all
```

Create now the new environment for HiCExplorer:

```
conda create --name hicexplorerEnvName hicexplorer=3.6 python=3.7 -c bioconda -c conda-forge
conda activate hicexplorerEnvName
hicDifferentialTAD --version
```
As `hicexplorerEnvName` you can select whatever name you like.

Best,

Joachim

**Comment by marizazh** [comment]
Thanks a million for the suggestions!!!
$hicDifferentialTAD --version
hicDifferentialTAD 3.6

P.S. I installed with python 2 just to test
