### ISSUE TITLE
hicPCA run of memory for 10kb resolution for Drosaphila

### ISSUE THREAD

**Issue by yancychy** [deeptools/HiCExplorer#672]
Hi, I want to run hicPCA for my hic data in h5 format with 10kb resolution and it failed.
I set 66 GB memory in HPC cluster. It was still killed by HPC. But I could run it at 50kb resolution with ICE normalization. Is there any solution for higher resolution? Thanks.

**Comment by joachimwolff** [comment]
Hi,

a) the obvious solution is to use more memory because 66 GB is not that much for a Hi-C analysis. The computation changes the sparse matrix to a dense one and that requires a lot of memory. Maybe try with 128 to 256 Gb, that should fix it.

b) You can compute the PCA only for a subset of chromosomes and concatenate the results later. If you have trouble with the amount of memory I suggest starting with one chromosome at the same time.

Best,

Joachim

**Comment by yancychy** [comment]
Thanks. I ran the PCA for single chromosomes separately. The final plot look weird. It is much differenct from the examples.
https://drive.google.com/file/d/1LbtDBG_9G7AmGAwUjR_7M_1sKqeHWd10/view?usp=sharing

**Comment by joachimwolff** [comment]
Please run the computation on a regular interaction matrix and not on a normalized matrix of a 0 - 1 range.

**Comment by yancychy** [comment]
Thanks. It works now.
