### ISSUE TITLE
hicPlotMatrix from .hic file issue

### ISSUE THREAD

**Issue by ptranvan** [deeptools/HiCExplorer#687]
Hi

I got a .hic file from Juicer/3d dna and would like to try HiCExplorer for nice heatmap figure, so I did:

`hic2cool convert input.hic output`

```
hicPlotMatrix -m output.mcool -o hicPlotMatrix.png 
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
Fontconfig error: Cannot load default config file
INFO:hicmatrix.lib.cool:Could not open cooler file. Maybe the path is wrong or the given node is not available.
INFO:hicmatrix.lib.cool:The following file was tried to open: output.mcool
INFO:hicmatrix.lib.cool:The following nodes are available: ['/resolutions/1000', '/resolutions/10000', '/resolutions/100000', '/resolutions/1000000', '/resolutions/25000', '/resolutions/250000', '/resolutions/2500000', '/resolutions/5000', '/resolutions/50000', '/resolutions/500000']
```
I am not sure to understand what is the correct way. Thanks for your help.

**Comment by joachimwolff** [comment]
Please familiar yourself with the data-structure of mcool files: https://cooler.readthedocs.io/en/latest/schema.html#multi-resolution

You need to define the resolution you are interested in because a mcool file contains multiple resolutions. However, this is for a cool file not necessary because it contains only a single resolution.
