### ISSUE TITLE
How to make the PC1 value more comparable accross chromosomes and samples

### ISSUE THREAD

**Issue by biozzq** [deeptools/HiCExplorer#709]
Dear @joachimwolff 

Usually, we want to identify the genomic regions with significantly changing PC1 values (namely switching compartments), thus i wonder that whether the PC1 values generated by using `hicPCA` are comparable accross chromosomes and samples? Here, the input matrices to `hicPCA` was only corrected by KR/ICE. Should normalization by sequence depth be made before correcting? Thank you very much.

Sincerely,
Zheng zhuqing

**Comment by joachimwolff** [comment]
> Usually, we want to identify the genomic regions with significantly changing PC1 values (namely switching compartments), thus i wonder that whether the PC1 values generated by using hicPCA are comparable accross chromosomes and samples? 

You can compare the value orientation, i.e. `<0` and `>0` of one chromosome with the identical chromosome of a different sample. They need to be correlated to a gene track otherwise the orientation could be inverted in one sample due to the nature of the eigenvalue and eigenvector computation.  
What is not possible is to directly and 1:1 compare one chromosome with a different chromosome. If you plan to make some comparisons, you need to have a good case why to do this. The statement e.g. 'chromosome 1 at region X has increase but chromosome 2 at region X not' is more or less useless; however sth like 'gene A is in B compartment in chromosome 1 and gene C in compartment A on chromosome 2 gives the conclusion foo' should be alright.

> Here, the input matrices to hicPCA was only corrected by KR/ICE. Should normalization by sequence depth be made before correcting?

Yes, we recommend normalizing to a similar read coverage before the correction step.

**Comment by biozzq** [comment]
Thank you for your explain.
