### ISSUE TITLE
hicPCA exhausting system resources and killed

### ISSUE THREAD

**Issue by OdysseyXD** [deeptools/HiCExplorer#717]
hi,

I've met a problem when using `hicPCA 3.4/3.5/3.6` to create pca1.bw and pca2.bw file, the program will **suddenly** exhausting system resources and then be killed. There's no any output. But it works well on `version 2.2` 

I believe this program termination is because of running out of Mem. But before this termination, is it normal to met the situation below for a small sampled test data even with `--chromosomes chr1`?
```bash
# 
conda create -n hicexplorer hicexplorer=3.6 python=3.8 -c bioconda -c conda-forge
conda activate hicexplorer
hicPCA -m ~/data/hic/XK_1030/dlohic_test/05-matrix/con1.cool -o pca1.bw pca2.bw -f bigwig

# 
killed 
```
![htop_result](https://user-images.githubusercontent.com/60571201/118745160-32aa0b80-b888-11eb-9fe2-48c34779e349.png)

**Comment by joachimwolff** [comment]
Hi,

Hi-C needs a lot of resources, and especially the PCA because we have to transform the matrix from a sparse one to a dense matrix. This is not avoidable, due to the mathematical properties of the algorithms. 

Concerning the resources and the error message: The software allocates memory, and the operating system grants these, or, if too many resources are requested, kills this process to keep the whole system alive. If the software gets killed, it is usually the case your system has too little memory available.  I see that you have 126 GB, which is usually enough, but for computations like this and with high-resolution matrices, it might be better to have 256 / 512 GB. However, please check if you really need to have the A/B compartments on this high resolution, maybe try with 100kb first and see if this is maybe already sufficient. Also have in mind, the higher the resolution, the less good are the correlations and therefore the PCA result is. That is simply caused by the mathematical properties of the Pearson correlation. 

We compute the PCA for each chromosome independently, and subsequential, therefore it does not matter if you define a list of chromosomes, except that the list of subsequently computed PCAs is shorter. 


What is your organism and what is the resolution you work with? Do you have a computer with more resources available? Maybe that is the simplest and time-saving move. 

Concerning the PCA with different HiCExplorer versions: The only major difference I see between the 3.X and the 2.2 version is the way we compute the observed/expected method. In 2.2 the default was the 'lieberman' way to compute it, while now it is the 'dist-norm'. You can apply the 2.2 behavior with the option `--method lieberman`.



Best,

Joachim

**Comment by OdysseyXD** [comment]
Thank you for your time! 

I'm learning and practicing to use hicexplorer, so at first  I did not realize that my `.cool` file is of 5kb resolution since it's build by another tool. Then I take your advices and use `file.mcool::resolutions/100000` to do the PCA analysis, it works both in v2.2 and v3.6. But I still have some questions.

1. hicPCA  still use all 72 threads of the cpu

    At 100kb resolution, hicPCA will not run out the MEM, but still take up all of the 72 threads. This situation happens both in v2.2 and v3.6, while hicexplorer v2.2 info me that the threads will be limited to 8.
```bash
INFO:numexpr.utils:Note: detected 72 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO:numexpr.utils:Note: NumExpr detected 72 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:hicmatrix.HiCMatrix:Number of poor regions to remove: 231638 {'chr1': 24595, 'chr2': 14518, 'chr3': 12409, 'chr4': 11110, 'chr5': 9122, 'chr6': 16525, 'chr7': 10868, 'chr8': 12694, 'chr9': 12454, 'chr10': 6154, 'chr11': 7444, 'chr12': 5633, 'chr13': 18632, 'chr14': 13189, 'chr15': 12495, 'chr16': 7416, 'chr17': 6194, 'chr18': 4767, 'chrX': 16947, 'chrY': 8453, 'chrNC_044959v2': 19}
INFO:hicmatrix.HiCMatrix:found existing 231638 nan bins that will be included for masking
```  
2. I can't reproduce the 5kb_resolution.cool PCA analysis both back in v2.2 or in v3.6 with `--method lieberman`

    Before I create this issue, I got three matrix file: `.hic`  `.mcool` files with multiple resolutions and a `.cool` file at 5kb resolution. And I indeed finished the `5kb.cool` hicPCA analysis and come out two `5kb_PCAx.bigwig` files(sized 2.4Mb, while `100kb_PCAx.bw` only 170kb). But when I turn to another sample's data of the same `5kb.cool` , program being killed. 
    Although the problem has been solved, thanks to your help, I still want to know why I can finish the PCA analysis at 5kb resoluiton  other than terminated due to a running out of memory at the very beginning. But I cannot reproduce the result anymore. So is that a coincidence to accidentally finish a 5kb PCA analysis under an "not enough memory" situation?

**Comment by joachimwolff** [comment]
We are using NumPy and Scipy to compute this and we do not have a direct influence on the thread usage or what warnings they throw. `INFO:numexpr.utils` that comes from NumPy, not from us. However, you can set some system environment variables that might control this: 

```
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
```

The number indicates the number of threads.  Execute these commands ONCE before you run any HiCExplorer tool. Please have in mind you change this behavior for all tools on your system that rely on these system environment variables. You can run this command as often as you like until you have reached your favorite number of threads. 

Second question:
There seem to be many issues at once. First, be careful with hic files, you need to convert the correction factors explicitly with hicConvertFormat, otherwise, they will not be applied. In case the correction factors are present in a correct way in the cool file, it could explain why you run out of memory, the application of these factors and to load a cool file requires some heavy memory usage. In this special case, I would need to profile it in detail to figure out why the usage is high. Again, your 126 GB of memory is quite a limiting factor for a 5 kb analysis. It might be better to switch to a computer with more resources. 
Than you write that it worked with 'another sample'. Please check here the read coverage and number of non-zero reads with `hicInfo`. It might be that the memory consumption comes from the read stage and therefore the coverage is important.
Also here the question: Do you have any other tools running on the same computer at the same time that might require memory too? Are you the only user of the computer or is it shared?
What I noticed in the source and I will add as a todo: We always read the fill cool matrix, but we could change the source to load only one chromosome in case we have a cool file that should reduce the memory requirements.

Best,

Joachim

**Comment by OdysseyXD** [comment]
Thanks again, and I will set those variables to limit the threads usage.

Actually, I'm dealing with DLO-HiC data, so I use [DLO-HiC-Tools](https://github.com/GangCaoLab/DLO-HiC-Tools) to pre-processing the Hi-C data (sampled 1Mb reads using seqtk). 

As for the correction factors, here's the result of `hicCovertFormat`:
```
INFO:hicexplorer.hicConvertFormat:Converting with hic2cool.
##########################
### hic2cool / convert ###
##########################
### Header info from hic
... Chromosomes:  ['All', 'chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chrX', 'chrY', 'chrNC_044959v2']
... Resolutions:  [2500000, 1000000, 500000, 250000, 100000, 50000, 25000, 10000, 5000]
... Normalizations:  ['VC', 'VC_SQRT', 'KR', 'SCALE']
... Genome:  /home/yyxu/data/genome/Sus.sizes
### Converting
... Resolution 100000 took: 0.741816520690918 seconds.
### Finished! Output written to: file_100000.cool
... This file is single resolution and NOT higlass compatible. Run with `-r 0` for multi-resolution.
```
As for `hicInfo`: 
I'm not quite understand the 'Size' and 'elements'
- Full Hi-C data
```bash
# Matrix information file. Created with HiCExplorer's hicInfo version 3.6
File:	hic/XK_1030/merged/R1/pipeout/05-matrix/con_1.cool
Date:	2021-05-18T14:25:34.428257
Genome assembly:	unknown
Size:	487,100
Bin_length:	5000
Chromosomes:length: chr1: 274330532 bp; chr2: 151935994 bp; chr3: 132848913 bp; chr4: 130910915 bp; chr5: 104526007 bp; chr6: 170843587 bp; chr7: 121844099 bp; chr8: 138966237 bp; chr9: 139512083 bp; chr10: 69359453 bp; chr11: 79169978 bp; chr12: 61602749 bp; chr13: 208334590 bp; chr14: 141755446 bp; chr15: 140412725 bp; chr16: 79944280 bp; chr17: 63494081 bp; chr18: 55982971 bp; chrX: 125939595 bp; chrY: 43547828 bp; chrNC_044959v2: 190584 bp; 
Number of chromosomes:	21
Non-zero elements:	33,444,749
The following columns are available: ['chrom' 'start' 'end']


Generated by:	cooler-0.8.11
```
- sampled Hi-C data
```bash
# Matrix information file. Created with HiCExplorer's hicInfo version 3.6
File:	hic/XK_1030/dlohic_test/pipeout/R1a/05-matrix/con_1.test.cool
Date:	2021-05-17T18:39:39.861758
Genome assembly:	unknown
Size:	487,100
Bin_length:	5000
Chromosomes:length: chr1: 274330532 bp; chr2: 151935994 bp; chr3: 132848913 bp; chr4: 130910915 bp; chr5: 104526007 bp; chr6: 170843587 bp; chr7: 121844099 bp; chr8: 138966237 bp; chr9: 139512083 bp; chr10: 69359453 bp; chr11: 79169978 bp; chr12: 61602749 bp; chr13: 208334590 bp; chr14: 141755446 bp; chr15: 140412725 bp; chr16: 79944280 bp; chr17: 63494081 bp; chr18: 55982971 bp; chrX: 125939595 bp; chrY: 43547828 bp; chrNC_044959v2: 190584 bp; 
Number of chromosomes:	21
Non-zero elements:	232,974
The following columns are available: ['chrom' 'start' 'end']


Generated by:	cooler-0.8.11
```

Finally, computer is shared and I'm not Administrator, so I have no idea if there were any memory consuming tools runing. Probablely somebody is using the computer, but I don't know the tools they're running.
