### ISSUE TITLE
TAD validation

### ISSUE THREAD

**Issue by hbandukw** [deeptools/HiCExplorer#746]
Hello,

I have identified TADs in my data at resolutions 500, 100 and 10 kb. I then used  _CTCF binding_ for merging the TADs. I am now trying to validate them visually and was hoping to get some advice/guidance. 

![siControl_C2C12_1_multires](https://user-images.githubusercontent.com/20444993/128342758-18ff2c9e-6302-4324-90ca-3b42c6684584.png)

Generally from the figure, I am unable to see any real correlation between the CTCF peaks and the identified TADs. I was wondering if that is normal? I should mention that my species is mouse. 

On another note, I was wondering why  "TAD separation score"  disappears towards the end of the x-axis in my figures? And how can I change the format from a heatmap to a profile plot?

Thanks in advance!

**Comment by joachimwolff** [comment]
Hi,

- please use a peak called file e.g. based on narrow or broadpeak. You have a raw file which makes it indeed difficult to see it.
- Please use different depth parameters for the Hi-C tracks in the different resolutions. 10 kb is ok, but the others not, maybe a depth value of a million or more works better. https://pygenometracks.readthedocs.io/en/latest/content/examples.html#examples-with-hi-c-data
- However, even in the given plot, the correlations are present! See the attached edited plot of yours. 
- Check the region you plot, only the start 90 - 94 Mb contains TADs, the rest is obviously closed compartment. 
- In this context: I guess your data is ChIP-Seq data, therefore it is 1D data, but better would be 2D data from HiChIP or similar protocols. Please also consider: CTCF is correlated to TAD boundaries but this does not mean that CTCF is exclusively present at TAD boundaries; neither it means all TAD boundaries have CTCF. For example, CTCF is involved in loop anchor points or in the DNA repair process. 

- TAD separation score: What position is the end of the chromosome you plotted? It seems to me there is simply no more data available, this would also match the different sizes of the 'missing area'. We also have here a short form posted to open an issue with very important points that you should post. You ignored this and I have therefore no information if you use the latest versions of HiCExplorer and pyGenomeTracks. Could be you use an outdated version and this bug is already fixed.
- matrix vs lines for the tad separation score: `type = lines`

Best,

Joachim

![2021-08-06_10-24](https://user-images.githubusercontent.com/13435136/128480863-737df5c3-0749-48e1-8940-42230bf2888d.png)

**Comment by hbandukw** [comment]
Hello,

hicexplorer 3.6, pyGenomeTracks 3.6

- The lines are based on a narrowPeak file and not the bigwig (see the bolded black lines between the bigwig and HiC snapshot),

- The depth for the matrices in the figure is 1 million, I will try to increase it further and see if the plot improves,

- Yup I see those, I guess I wanted to double-check whether those were valid correlations or not.

- TAD separation score: The region I plotted was: 1:90000000-99000000.

Thanks,
Hina

**Comment by joachimwolff** [comment]
Hi Hina,

- it does not matter what file format is used, but the content does. What I wanted to say with the 'narrowpeak' file is that I recommend using a peak called file. Your plot looks like raw data is used, and not that peaks have been called. If peaks have been called, I recommend a higher threshold. Too many data points that are not peaks are still part of the data, e.g., 94 - 97.5 Mb region.
- To validate, I also recommend the tool `hicValidateLocations` with the TAD mode. However, this is only accessible in the latest HiCExplorer version 3.7.
- Especially for the 500 kb, I recommend trying then maybe 10 Mio, but this you need to figure out via try & error. The important part is that you see the structures, which you do for 10 kb, partially for 100kb, and not for 500 kb. Would you please use a different depth value for the different resolutions?
- The region: Maybe @lldelisle does know here more?

Best,

Joachim

**Comment by lldelisle** [comment]
Hi Hina,
- First of all, TADs are structure which are around 1Mb length in mouse genome so it is expected that you cannot identify them with 500kb bins. You will detect larger domains at this resolution but they are not TADs.
- It looks like the TAD separation score is not displayed at the end depending of which size of bin you used. I guess this is a border effect. I think it is because only the last value of the TAD separation score of the region plotted is shown and it is shown on the left of the bin... I should probably change this... Generally speaking, the separation scores are more easy to read with `type = lines` as @joachimwolff suggested.
- For the correlation between CTCF and TAD borders. 
Bonev et al. 2017 showed that only a portion of CTCF binding sites are at boundaries:
![image](https://user-images.githubusercontent.com/30404086/128519429-eb0dc791-b581-4a75-8020-2ab41983982d.png)
- For the number of vertical lines. That's true that there are a lot but I am also not familiar with so broad regions.
Best,
Lucille

**Comment by joachimwolff** [comment]
No more feedback from the user. Closing.
